language: node_js

node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# safelist
branches:
  only:
  - master

before_script:
  - npm install -g firebase-tools

script:
  - cd functions && npm install && cd ../

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
